### PR TITLE
feat: ignore buffers that are of the type `nofile`, `prompt`, `terminal`

### PR DESCRIPTION
**Pull request by stevenxxiu**
This fixes:

- #1
- A part of #2. For *Neogit* with *diffview* integration enabled, this errors out when quitting a *diffview* diff.

### CODE REVIEW

**Comment by lukoshkin** [comment]
Hey, @stevenxxiu!
I saw you PR! But I haven't time to test it and merge it. I have some amends that I'd like to do. I will add them on top of your PR and then we'll merge it. But currently, I have little time on my hands. I think I will resolve it in one or two weeks. Sorry

**Comment by stevenxxiu** [comment]
No worries, hope you enjoyed your holiday! You can add comments and I can update my PR too if you wish.

**Comment by lukoshkin** [comment]
I wrapped duplicated code pieces into functions. This made `init.lua` module more concise and readable. And with new `wrap_fn.lua`, I will be able to fallback to the previous implementation in case of any setbacks with this one. @stevenxxiu, now you can check whether old problems trouble you and if new ones emerged!

**Comment by stevenxxiu** [comment]
Thanks for the refactor.

Not sure if this is related, but when I go in *Neogit* *diffview*, focus on some file contents, then exit, I get the error:

```
E5108: Error executing lua vim/_editor.lua:0: nvim_exec2()..BufHidden Autocommands for "*": Vim(append):Error executing lua callback: Vim:E957: Invalid window number
stack traceback:
        [C]: in function 'getmatches'
        ...y/highlight-whitespace/lua/highlight-whitespace/core.lua:102: in function 'fn'
        ...ighlight-whitespace/lua/highlight-whitespace/wrap_fn.lua:11: in function 'callback'
        ...y/highlight-whitespace/lua/highlight-whitespace/init.lua:22: in function <...y/highlight-whitespace/lua/highlight-whitespace/init.lua:21>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...re/nvim/lazy/neogit/lua/neogit/integrations/diffview.lua:20: in function 'close'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...re/nvim/lazy/neogit/lua/neogit/integrations/diffview.lua:20: in function 'close'
        [string ":lua"]:1: in main chunk
```

**Comment by lukoshkin** [comment]
Hey!
I haven't tried it with Neogit. But I will take a look. Maybe I'll switch to Neogit myself in the end. Had you met the same error before I refactored your changes. Or maybe the changes caused this behaviour? @stevenxxiu

**Comment by stevenxxiu** [comment]
I can't quite remember. Looking at your changes I don't think it causes it, but I never looked at this issue before. I can take a look later. 

Oh and it's *Neogit* with the *diffview* plugin that they support, to view side-by-side diffs.

**Comment by stevenxxiu** [comment]
The refactor commit indeed causes the bug. I'm not sure what the cause is.

**Comment by stevenxxiu** [comment]
I found another way to replicate the issue, that happens even without the refactor commit. Run `:checkhealth`, then close the window. We get:

```
Error detected while processing BufHidden Autocommands for "*":
Error executing lua callback: Vim:E957: Invalid window number
stack traceback:
        [C]: in function 'getmatches'
        ...y/highlight-whitespace/lua/highlight-whitespace/core.lua:103: in function 'save_matches_to_cache_and_clear'
        ...y/highlight-whitespace/lua/highlight-whitespace/init.lua:55: in function <...y/highlight-whitespace/lua/highlight-whitespace/init.lua:51>
```

I made a fix to the issue that appears to work. Not sure if this fix makes sense.

**Comment by lukoshkin** [comment]
I reviewed the function you referred to. I think there were a few issues with it:
1. There was just one check (whether a window where a buffer had been loaded before it got hidden was floating or not) and it controlled just `clearmatches` function and not touched caching results of `getmatches`
2. `clearmatches` was no parameters passed to it - what might cause issues (e.g., I don't know which window is current when this function is called)

```lua
function M.save_matches_to_cache_and_clear(args)
  local bnr = (args or {}).buf or api.nvim_get_current_buf()
  local wid = fn.bufwinid(bnr)

  if
    not api.nvim_buf_get_option(bnr, "modifiable")
    or api.nvim_win_get_config(wid).relative ~= ""
  then
    return
  end

  fn.clearmatches(wid)
  local bname = api.nvim_buf_get_name(bnr)
  M.buffer_cached_matches[bname] = fn.getmatches(wid)
  M.win_group_match[bname] = nil
end
```

About reproducibility with `checkhealth`. I wasn't able to reproduce it. Likely because we have different settings/ different set of plugins and so on. But let's check if the snippet above solves your problems. You can first try it as it is. And if it does not help, you can add `pcall` wrapping
@stevenxxiu

**Comment by stevenxxiu** [comment]
I tried your new function, and there's a new error:

```
E5108: Error executing lua vim/_editor.lua:0: nvim_exec2()..BufHidden Autocommands for "*": Vim(append):Error executing lua callback: ...y/highlight-whitespace/lua/highlight-whitespace/core.lua:104: Invalid window id: -1
stack traceback:
        [C]: in function 'nvim_win_get_config'
        ...y/highlight-whitespace/lua/highlight-whitespace/core.lua:104: in function 'fn'
        ...ighlight-whitespace/lua/highlight-whitespace/wrap_fn.lua:11: in function 'callback'
        ...y/highlight-whitespace/lua/highlight-whitespace/init.lua:22: in function <...y/highlight-whitespace/lua/highlight-whitespace/init.lua:21>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...re/nvim/lazy/neogit/lua/neogit/integrations/diffview.lua:20: in function 'close'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...re/nvim/lazy/neogit/lua/neogit/integrations/diffview.lua:20: in function 'close'
        [string ":lua"]:1: in main chunk
```

Taking a guess, the `:checkhealth` issue could be due to using this with *bufferline*.

Unrelated, but my LSP says `api.nvim_buf_get_option()` is deprecated. You can use `api.nvim_get_option_value("modifiable", { buf = bnr })` instead.

**Comment by lukoshkin** [comment]
Let's check this snippet :)
```lua
function M.save_matches_to_cache_and_clear(args)
  local bnr = (args or {}).buf or api.nvim_get_current_buf()
  local wid = fn.bufwinid(bnr)

  if
    not api.nvim_get_option_value("modifiable", { buf = bnr })
    or api.nvim_win_get_config(wid).relative ~= ""
  then
    return
  end

  local ok, matches = pcall(fn.getmatches, wid)
  if ok then
    local bname = api.nvim_buf_get_name(bnr)
    M.buffer_cached_matches[bname] = matches
    M.win_group_match[bname] = nil
  end
end
```
Btw, which LSP do you use for lua code?
@stevenxxiu

**Comment by stevenxxiu** [comment]
The error is in the call to `nvim_win_get_config()`. So if you just want a `pcall()`, I think this works:

```lua
function M.save_matches_to_cache_and_clear(args)
  local bnr = (args or {}).buf or api.nvim_get_current_buf()
  local wid = fn.bufwinid(bnr)

  if not api.nvim_get_option_value("modifiable", { buf = bnr }) then
    return
  end

  local ok, config = pcall(api.nvim_win_get_config, wid)
  if not ok then
    return
  end

  if config.relative ~= "" then
    return
  end

  local bname = api.nvim_buf_get_name(bnr)
  M.buffer_cached_matches[bname] = matches
  M.win_group_match[bname] = nil
end
```

I use *lazydev* for my LSP.

**Comment by stevenxxiu** [comment]
The error is in the call to `nvim_win_get_config()`. So if you just want a `pcall()`, I think this works:

```lua
function M.save_matches_to_cache_and_clear(args)
  local bnr = (args or {}).buf or api.nvim_get_current_buf()
  local wid = fn.bufwinid(bnr)

  if not api.nvim_get_option_value("modifiable", { buf = bnr }) then
    return
  end

  local ok, config = pcall(api.nvim_win_get_config, wid)
  if not ok or config.relative ~= "" then
    return
  end

  local bname = api.nvim_buf_get_name(bnr)
  M.buffer_cached_matches[bname] = fn.getmatches(wid)
  M.win_group_match[bname] = nil
end
```

I use *lazydev* to set up my LSP.

**Comment by lukoshkin** [comment]
Hmm, if this error is about non-existing window id, maybe it is better than just to check the returned value from `fn.bufwinid`?
```lua
function M.save_matches_to_cache_and_clear(args)
  local bnr = (args or {}).buf or api.nvim_get_current_buf()
  local wid = fn.bufwinid(bnr)

  if
    wid < 0
    or api.nvim_win_get_config(wid).relative ~= ""
    or not api.nvim_get_option_value("modifiable", { buf = bnr }) then
    return
  end

  local bname = api.nvim_buf_get_name(bnr)
  M.buffer_cached_matches[bname] = fn.getmatches(wid)
  M.win_group_match[bname] = nil
end
```
@stevenxxiu

**Comment by stevenxxiu** [comment]
> Hmm, if this error is about non-existing window id, maybe it is better than just to check the returned value from `fn.bufwinid`?

Indeed that works! I didn't know about this. Thanks for telling me.

**Comment by lukoshkin** [comment]
@stevenxxiu
I'm glad I was able to help you remotely, without even reproducing the problem locally, on my machine

What other issues (related to this PR) do you have? I guess the last snippet solved some of your problems. Are we close to merging PR? If yes, you can update the code (by adding also the last snippet), push the commit, and I will merge the PR

**Comment by stevenxxiu** [comment]
I copied over your last snippet and made a commit.

I can't see any other issues for now.

**Review by lukoshkin — APPROVED** [review]

**Pull request merged**
